on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  get-screen-shots:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 19
          check-latest: true
      - run: npm i -g pnpm@latest
      - run: pnpm i
      - run: pnpm run pre:dev
      - run: pnpm run screenshots
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - uses: EndBug/add-and-commit@v9
        with:
          author_name: ${{ github.actor }}
          author_email: ${{ github.actor }}@users.noreply.github.com
          message: 'chore: update screenshots'
          add: 'screenshots'
          push: true
          branch: ${{ github.head_ref }}
